### PR TITLE
Switch base image to RHEL7 UBI minimal

### PR DESCRIPTION
**Pull request by croomes**
Required for certification, passes scan.

### CODE REVIEW

**Comment by croomes** [comment]
Test are failing with:
```
(microdnf:1): libdnf-WARNING **: 16:34:22.010: Skipping refresh of latest-rhah-ubi-7.6: cannot update repo 'latest-rhah-ubi-7.6': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (28): Timeout was reached for ftp://partners.redhat.com/1c5d859a/UBI-5032b19e400c3605214630e4ba65e14f/7/RHAH-UBI/x86_64/repodata/repomd.xml [Connection time-out]
```
Seems ftp doesn't work well on Travis:
```

**Comment by croomes** [comment]
Build failing with:
```
(microdnf:1): libdnf-WARNING **: 16:33:51.760: Skipping refresh of latest-rhubi-7.6: cannot update repo 'latest-rhubi-7.6': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (28): Timeout was reached for ftp://partners.redhat.com/1c5d859a/UBI-5032b19e400c3605214630e4ba65e14f/7/RHUBI/x86_64/repodata/repomd.xml [Connection time-out]
```
Seems Travis doesn't like ftp: https://blog.travis-ci.com/2018-07-23-the-tale-of-ftp-at-travis-ci  (TL/DR: use http).  Repos aren't available on http...

**Comment by darkowlzz** [comment]
With this change, the operator image size increases from 35MB to 116MB.
I'm thinking about using alpine for k8s and the new base image for openshift only.
We can have different target builds and use the new base for tests on openshift only.
Or maybe 116MB is a good enough size?

**Comment by darkowlzz** [comment]
Discussed and decided to have a single image for simplicity.

**Pull request merged**
