### PR TITLE
Add CSI helper deployment options

### PR DESCRIPTION
**Pull request by darkowlzz**
Adds a new attribute `HelperDeployment` to `StorageOSClusterCSI` for
setting the kind of deployment, keeping the default to StatefulSet.

Combines the existing StatefulSet deployment with new Deployment into CSIHelper group of methods.
Adds pod toleration of 30 seconds for quick recovery on node failures.

Updates all the unit tests to test for CSI helper deployments.

Updates all the OLM related manifest files for CSI helper deployment support.

### CODE REVIEW

**Comment by darkowlzz** [comment]
Need to update the operator e2e tests to include CSI helper deployment case.

**Comment by darkowlzz** [comment]
The deployment manifest files update is done using the helper scripts from #120 . Seems to work great.
Updated `deploy/storageos-operators.configmap.yaml` with all the CRD and OLM changes and ran `make metadata-update` to automatically update all the other files https://github.com/storageos/cluster-operator/pull/124/commits/62a1929cecb1cd2d8a9b3c0b7c197c6292f48789 .

**Comment by croomes** [comment]
It probably needs a README change for the new param?  Will also need a docs change.

cc @actionbuddha @avestuk @Arau

**Comment by darkowlzz** [comment]
This will increase the CI test time for both operator-sdk e2e tests and OLM e2e tests because of running an extra set of tests for CSI helpers as Deployment.

Renamed `csi.helperDeployment` to `csi.deploymentStrategy`.

**Pull request merged**
