### PR TITLE
Fix apiManagerContainer tag in v1 deploy CRD

### PR DESCRIPTION
**Pull request by mhmxs**
`apiControllerContainer` was an invalid image name.

### CODE REVIEW

**Review by croomes — APPROVED** [review]
Nicely spotted!

**Comment by darkowlzz** [comment]
We added docker login in CI to avoid failures due to image pull limitation but looks like login fails for PRs created by users who aren't part of travisCI org or registered. Maybe the credentials aren't being shared.
I'm not sure of a better way to do it. Maybe attempt to login and continue even if it fails? That way, if the login fails and docker hub limits are not reached, the CI will still function.

**Comment by darkowlzz** [comment]
@mhmxs can you try adding `|| true` in https://github.com/storageos/cluster-operator/blob/690bced03f2cebc89a6dd5d877b1f81964db53e4/.travis.yml#L55 and the second login in the deploy stage?

**Comment by mhmxs** [comment]
> The CI keeps on waiting for some input:

Experienced the same :D

**Comment by mhmxs** [comment]
Tracked here: https://github.com/storageos/cluster-operator/pull/320

**Pull request closed without merging**
